// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxaq7H81pLOqV1_FHNIcJhlgJDqgOcgHQ',
    appId: '1:939971319414:ios:39579db6efd60f1aecb157',
    messagingSenderId: '939971319414',
    projectId: 'fruits-time-uz',
    storageBucket: 'fruits-time-uz.firebasestorage.app',
    iosBundleId: 'uz.khberv.fruitstime',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0m0XmHZIw_ftEUObfseSkGvikEP4nryQ',
    appId: '1:939971319414:android:ac3afdd0d6302674ecb157',
    messagingSenderId: '939971319414',
    projectId: 'fruits-time-uz',
    storageBucket: 'fruits-time-uz.firebasestorage.app',
  );
}
